services:
  qemu:
    image: qemux/qemu
    container_name: qemu
    environment:
      BOOT: "https://download.fydeos.io/v20.0/FydeOS-VMware-v20.0-Preview1-io.ova"
      RAM_SIZE: "12G"
      CPU_CORES: "4"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
    volumes:
      - ./qemu:/storage
    restart: always
    stop_grace_period: 2m
