services:
  qemu:
    image: qemux/qemu
    container_name: qemu
    environment:
      BOOT: "https://download1320.mediafire.com/opyf0ed5n9pgZJP4Xrusyu9PHnypPc4xYMGNQTMk3f5cAvEt_yWGY1j04veOksgo4LzOjXLYcpV9Ebkw-CVKV8DySE-P_t40ECoNE2Eo73wrZn-0TtPEyj9H1sGf8xPgYK3gfHoebJpAWdlqIfY2UtZottYuM_Hk6p96IXlroQ/asp12tmmxbdr5zd/chromeos_16371.49.0_reven_recovery_stable-channel_mp-v8.iso"
      RAM_SIZE: "12G"
      CPU_CORES: "4"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
    volumes:
      - ./qemu:/storage
    restart: always
    stop_grace_period: 2m
